services:
  ai-job:
    container_name: "ai-job"
    build:
      context: .
      dockerfile: Dockerfile
    image: "ai-job:1.0"
    env_file:
      - ../../../../../.env
    ports:
      - "9100:9100"
      - "6768:6768"
    volumes:
      - ./logs:/app/logs
    command: '/app/ai-job.jar --smart.config.webui.port=6768 --smart.config.desc.infer=true'
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ai_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
